ALTER TABLE users ADD COLUMN created_at TIMESTAMP;
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP;
DO $$
DECLARE t TIMESTAMP;
BEGIN
t := CURRENT_TIMESTAMP;
UPDATE users SET created_at = t, updated_at = t;
END $$;
ALTER TABLE users ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE users ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE users ADD COLUMN first_name VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN last_name VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN last_ip VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN last_login TIMESTAMP DEFAULT NULL;